common:
  batch_size: 64
  is_restore: False
  restore_ind: ""
  restore_ckpt: ""
  preview_batch: 10000
  restore_all_states: False

global_settings:
  image_size: [416, 416]

trainer:
  max_epochs: 20
  precision: bf16-mixed
  val_check_interval: 1.0
  gradient_clip_val: 5
  accumulate_grad_batches: 1
  accelerator: gpu
  devices: [0]

model:
  name: ObjectDetectionModel
  backbone:
    name: TimmBackbone
    options:
      name: lcnet_100
      pretrained: True
      features_only: True
  neck:
    name: YOLOv3Neck
    options:
      name: FPN
      out_channels: 512
      in_indices: [2, 3, 4]
  head:
    name: YOLOv3Head
    options:
      in_channels_list: [512, 512, 512]
      num_classes: 80
      anchors: &coco_anchors
        - [10, 13]
        - [16, 30]
        - [33, 23]
        - [30, 61]
        - [62, 45]
        - [59, 119]
        - [116, 90]
        - [156, 198]
        - [373, 326]
      anchor_masks: &coco_anchor_masks
        - [0, 1, 2]
        - [3, 4, 5]
        - [6, 7, 8]
      strides: &coco_strides [8, 16, 32]
  postprocessor:
    eval:
      name: YOLOv3Postprocessor
      options:
        anchors: *coco_anchors
        anchor_masks: *coco_anchor_masks
        strides: *coco_strides
        num_classes: 80
        conf_thres: 0.001
        iou_thres: 0.65
        max_det: 300
    vis:
      name: YOLOv3Postprocessor
      options:
        anchors: *coco_anchors
        anchor_masks: *coco_anchor_masks
        strides: *coco_strides
        num_classes: 80
        conf_thres: 0.25
        iou_thres: 0.45
        max_det: 300
  loss:
    name: YOLOv3Loss
    options:
      img_dim: 416
      anchors: *coco_anchors
      anchor_masks: *coco_anchor_masks
      strides: *coco_strides
      num_classes: 80
      lambda_coord: 5.0
      lambda_noobj: 0.5
      ignore_iou_thr: 0.7
      noobj_iou_thr: 0.1
      loss_normalize: batch

dataset:
  train_options:
    name: CentralDataset
    options:
      mode: train
      image_size: -1
      aug_ratio: 0.5
      return_tensor: True
      length_of_dataset: -1
  valid_options:
    name: CentralDataset
    options:
      mode: val
      image_size: -1
      aug_ratio: 0
      return_tensor: True
      length_of_dataset: -1

dataloader:
  train_options:
    batch_size: -1
    num_workers: 24
    persistent_workers: True
  valid_options:
    batch_size: -1
    num_workers: 24
    shuffle: False
    drop_last: False

optimizer:
  name: AdamW
  options:
    lr: 1.0e-3
    betas: [0.9, 0.999]
    weight_decay: 0.0001

lr_scheduler:
  name: PolynomialLRWarmup
  options:
    warmup_iters: -1
    total_iters: -1
  pl_options:
    monitor: loss
    interval: step

# lr_scheduler:
#   name: MultiStepLRWarmUp
#   options:
#     warmup_milestone: 5000
#     milestones: [1000000, 2000000]
#     gamma: 0.316227766
#   pl_options:
#     monitor: loss
#     interval: step

callbacks:
  - name: ModelCheckpoint
    options:
      monitor: "val/map"
      mode: max
      verbose: True
      save_last: True
      save_top_k: 5
  - name: LearningRateMonitor
    options:
      logging_interval: step
  - name: RichModelSummary
    options:
      max_depth: 3
  - name: CustomTQDMProgressBar
    options:
      unit_scale: -1

logger:
  name: TensorBoardLogger
  options:
    save_dir: logger
